language: node_js

node_js:
  - 6
  - 7

matrix:
  fast_finish: true

cache:
  yarn: true
  directories:
    - node_modules
notifications:
  slack:
    secure: X2mrk0UT9PY3iQJq+Pn55dx273irrTbB5xqs0FlG/6ks9NcTIL9nr/PDGN8pNSrgZwbprCZ/ZJ8zwIvQugt/SJ5dDb8C2OaIM79rPWs4tbuGYrT4pbyQeY+W4if1V5nti5xNmcb9GMKzMJAOzRdHKT3a14OlXMDavJ1e5uTyqihZ/kRuFuKloujHRoytFBy65pFGK5bhLkKrUF+q+JJs4pG7tX2WVr1aOXdZyZELNxjncYX3yCU+dlI5AZHoaZv8buvrdQHoUVTvxzb39la3D7gkiY/A3zaTZs2QBeUbdLEPZWSPJVnPc5pbq0UwTd/HA6Sl2PtI+ra4D5n7ud+gW9dsmhBJ2P+aiOmDwYaCgMzHrL0yEIe5wHhqW+BYHFfXv1sY4wkspQIDmOeiLS2YM/UcvJ91nBZZTcIiVC0pMlP9QRmWv6/ZseMxj7bYwyPIEO2bik/W8eoE9ms/AWzJ0XR34YJ5f2rzEaCBJim7PcGvPCWX/lmWATZdAdZ30sdCGJuiYgXYSw9ma3nsaBZsnVXM+GQq+fA8aM9xELc8sFy0wZjJXa3KPulMaCTqDg4gD9TUAi4gZeCpMBWyDBb8a1M5Jwjax7q5KWYOkSkfx4twyRAZL8Uv51OV4LsCFOIIZrNZTEQymrmqoJ6dRZzpfHg92UpxZoziKe23OPrUtQo=
