language: node_js
node_js:
- 6
- 7
- 8
matrix:
  fast_finish: true
cache:
  - ~/.npm
notifications:
  slack:
    secure: BtcG9bobagkYgZ5aDp0lHXgMXDY2Qnmy7hnaJTj5H5lDYTWIOwT1gHfnpUfiNfdBCNv7vZnqP1x3vHDlNsovcYL31p2YIbsC6s35Nhm+BVaRLEGQ9AHKdvK7LJVGRNPh4LR1wMs2uAn/jiTZTksDieEtoi29gLBbRNzzDYpih7lBvhsrb/fyuRsseityRlyLg/4qYg3n/60drd5Hd0foeQdoeGLjKFSdB4oayVMw+cf3EBKG3sfb4NpnL4n0XUs1UWxt7YIa9B226UFiNoLNXqW/yDjUwovddtlxKsCUyzS2c/aAWZlEUOlYmi87v6NDaC3l/fP7wmH8F5phr87Wvr3NVT/SiBRNzbvDaZFwR8l4I2oikwlcbezTDrweRcYZc1/w5CnasaGP0TBk+mhRnHZWUND7XTEhJTg3Aq/MhgCOLnIweX7HMEqJf3u3BBp0OCg43RQXGBId0izRnTdLXd+qX4VBgiiJudjalfNZQoc5hEQsbKM0k6M6j2H9ZwU0V3XgM5z90dQUIOw9xfJ7digfO1JYQEvWrXqHu2rBxXmIQ4bEHU4yBxCaiQTl6PxJPwInd8QdeZYT7nstugHICxkZErXHhq95eVL3wKjiYi8k8eOslFFQu+38qdjbLmuV5kkeOfphOycj6IMxHVXMP9wwCoVq3k4wg75Dv6rvBTI=
